name: hotel
description: "Проект"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # state management
  flutter_bloc: ^8.1.3
  device_preview: ^1.1.0

  # comparing dart objects
  equatable: ^2.0.5

  # service locator
  get_it: ^7.6.7

  # database
  floor: ^1.4.2

  # retrofit
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # bottom navigation
  persistent_bottom_nav_bar: ^5.0.2

  # icons from figma
  flutter_svg: ^2.0.9

  cached_network_image: ^3.3.1
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  floor_generator: ^1.4.2
  retrofit_generator: ^7.0.8
  build_runner: ^2.1.2
  json_serializable: ^6.6.2

flutter:


  uses-material-design: true

  assets:
    - assets/icons/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/inter_bold.ttf
          weight: 700
        - asset: assets/fonts/inter/inter_semibold.ttf
          weight: 600
        - asset: assets/fonts/inter/inter_medium.ttf
          weight: 500
        - asset: assets/fonts/inter/inter_regular.ttf
          weight: 400